"""initial

Revision ID: a792cae08e25
Revises: 
Create Date: 2024-07-10 12:14:12.694067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a792cae08e25'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_category',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=55), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('npp', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['shop_category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_shop_category_id'), 'shop_category', ['id'], unique=False)
    op.create_table('shop_color_beer',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=55), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_color_beer_id'), 'shop_color_beer', ['id'], unique=False)
    op.create_table('shop_color_vine',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=55), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_color_vine_id'), 'shop_color_vine', ['id'], unique=False)
    op.create_table('shop_country',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=55), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_country_id'), 'shop_country', ['id'], unique=False)
    op.create_table('shop_shop',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('shop', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=55), nullable=False),
    sa.Column('work_date', sa.String(length=255), nullable=False),
    sa.Column('geo_coords', sa.String(length=255), nullable=False),
    sa.Column('npp', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_shop_id'), 'shop_shop', ['id'], unique=False)
    op.create_table('shop_sugar',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=55), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_sugar_id'), 'shop_sugar', ['id'], unique=False)
    op.create_table('shop_product',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=2500), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('strenght', sa.Float(), nullable=True),
    sa.Column('npp', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('country_id', sa.String(), nullable=True),
    sa.Column('color_vine_id', sa.String(), nullable=True),
    sa.Column('color_beer_id', sa.String(), nullable=True),
    sa.Column('sugar_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['shop_category.id'], ),
    sa.ForeignKeyConstraint(['color_beer_id'], ['shop_color_beer.id'], ),
    sa.ForeignKeyConstraint(['color_vine_id'], ['shop_color_vine.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['shop_country.id'], ),
    sa.ForeignKeyConstraint(['sugar_id'], ['shop_sugar.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_shop_product_id'), 'shop_product', ['id'], unique=False)
    op.create_table('shop_image',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('code_owner', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('img_name', sa.String(), nullable=False),
    sa.Column('npp', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['code_owner'], ['shop_product.id'], ),
    sa.PrimaryKeyConstraint('id', 'code_owner')
    )
    op.create_index(op.f('ix_shop_image_code_owner'), 'shop_image', ['code_owner'], unique=False)
    op.create_index(op.f('ix_shop_image_id'), 'shop_image', ['id'], unique=False)
    op.create_table('shop_shop_product',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('shop_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('stock', sa.String(), nullable=False),
    sa.Column('quantity_thershold', sa.Integer(), nullable=False),
    sa.Column('price', sa.DECIMAL(scale=3), nullable=False),
    sa.Column('price_time', sa.DateTime(), nullable=False),
    sa.Column('price_old', sa.DECIMAL(scale=3), nullable=False),
    sa.Column('price_from', sa.DECIMAL(scale=3), nullable=False),
    sa.Column('stock_qty', sa.Integer(), nullable=False),
    sa.Column('npp', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['shop_product.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shop_shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_shop_product_id'), 'shop_shop_product', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_shop_product_id'), table_name='shop_shop_product')
    op.drop_table('shop_shop_product')
    op.drop_index(op.f('ix_shop_image_id'), table_name='shop_image')
    op.drop_index(op.f('ix_shop_image_code_owner'), table_name='shop_image')
    op.drop_table('shop_image')
    op.drop_index(op.f('ix_shop_product_id'), table_name='shop_product')
    op.drop_table('shop_product')
    op.drop_index(op.f('ix_shop_sugar_id'), table_name='shop_sugar')
    op.drop_table('shop_sugar')
    op.drop_index(op.f('ix_shop_shop_id'), table_name='shop_shop')
    op.drop_table('shop_shop')
    op.drop_index(op.f('ix_shop_country_id'), table_name='shop_country')
    op.drop_table('shop_country')
    op.drop_index(op.f('ix_shop_color_vine_id'), table_name='shop_color_vine')
    op.drop_table('shop_color_vine')
    op.drop_index(op.f('ix_shop_color_beer_id'), table_name='shop_color_beer')
    op.drop_table('shop_color_beer')
    op.drop_index(op.f('ix_shop_category_id'), table_name='shop_category')
    op.drop_table('shop_category')
    # ### end Alembic commands ###
